//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LM2ItemTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string BackgroundColour {
            get {
                return ((string)(this["BackgroundColour"]));
            }
            set {
                this["BackgroundColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string MantraTextColour {
            get {
                return ((string)(this["MantraTextColour"]));
            }
            set {
                this["MantraTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string ItemFillColour {
            get {
                return ((string)(this["ItemFillColour"]));
            }
            set {
                this["ItemFillColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
</ArrayOfBoolean>")]
        public bool[] WeaponsLayout {
            get {
                return ((bool[])(this["WeaponsLayout"]));
            }
            set {
                this["WeaponsLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
</ArrayOfBoolean>")]
        public bool[] UseItemLayout {
            get {
                return ((bool[])(this["UseItemLayout"]));
            }
            set {
                this["UseItemLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
</ArrayOfBoolean>")]
        public bool[] EquipItemLayout {
            get {
                return ((bool[])(this["EquipItemLayout"]));
            }
            set {
                this["EquipItemLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
</ArrayOfBoolean>")]
        public bool[] OtherItemLayout {
            get {
                return ((bool[])(this["OtherItemLayout"]));
            }
            set {
                this["OtherItemLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
  <boolean>true</boolean>
</ArrayOfBoolean>")]
        public bool[] SoftwareLayout {
            get {
                return ((bool[])(this["SoftwareLayout"]));
            }
            set {
                this["SoftwareLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("340")]
        public int WindowWidth {
            get {
                return ((int)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int WindowHeight {
            get {
                return ((int)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SilhouetteMode {
            get {
                return ((bool)(this["SilhouetteMode"]));
            }
            set {
                this["SilhouetteMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRecent {
            get {
                return ((bool)(this["ShowRecent"]));
            }
            set {
                this["ShowRecent"] = value;
            }
        }
    }
}
